/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    doctors: Doctor;
    categories: Category;
    'blog-posts': BlogPost;
    'youtube-videos': YoutubeVideo;
    inquiries: Inquiry;
    clients: Client;
    appointments: Appointment;
    'follow-ups': FollowUp;
    consultations: Consultation;
    reports: Report;
    'email-outbox': EmailOutbox;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'youtube-videos': YoutubeVideosSelect<false> | YoutubeVideosSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'follow-ups': FollowUpsSelect<false> | FollowUpsSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'email-outbox': EmailOutboxSelect<false> | EmailOutboxSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    'clinic-info': ClinicInfo;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'clinic-info': ClinicInfoSelect<false> | ClinicInfoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Role-based access level. Only Admins can modify user roles.
   */
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alternative text for accessibility and SEO.
   */
  alt: string;
  caption?: string | null;
  /**
   * Access visibility. Private files are guarded server-side against public access.
   */
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Unique URL identifier for this service (e.g. dental-implants, cosmetic-dentistry).
   */
  slug: string;
  /**
   * Concise summary displayed on service cards and navigation overviews (max 250 chars).
   */
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * Icon identifier mapped in the clinic design system (e.g. tooth, smile, shield, clock).
   */
  iconName?: string | null;
  /**
   * Controls display order on the website (lowest number first).
   */
  order?: number | null;
  /**
   * Unchecking hides this service from public visitors while keeping it for administration.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  name: string;
  slug: string;
  /**
   * Specialty designation (e.g. Lead Implantologist & Cosmetic Dentist).
   */
  title: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo: number | Media;
  specialties?: (number | Service)[] | null;
  qualifications?:
    | {
        degree: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary for article cards and search snippets (max 300 chars).
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  category: number | Category;
  author?: (number | null) | Doctor;
  publishedAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-videos".
 */
export interface YoutubeVideo {
  id: number;
  title: string;
  /**
   * Full YouTube watch link (e.g. https://www.youtube.com/watch?v=...)
   */
  youtubeUrl: string;
  thumbnail?: (number | null) | Media;
  category?: (number | null) | Category;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  fullName: string;
  phone: string;
  email: string;
  service?: (number | null) | Service;
  preferredDate?: string | null;
  preferredTime?: ('morning' | 'afternoon' | 'evening') | null;
  message?: string | null;
  /**
   * Tracking status for clinic reception and staff.
   */
  status: 'new' | 'contacted' | 'scheduled' | 'archived';
  /**
   * Internal administrative communication regarding this patient inquiry.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  fullName: string;
  phone: string;
  email?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female') | null;
  address?: string | null;
  emergencyContact?: {
    name?: string | null;
    relationship?: string | null;
    phone?: string | null;
  };
  status: 'active' | 'inactive' | 'archived';
  /**
   * Administrative and operational clinic notes only. Strictly hidden from patient.
   */
  internalNotes?: string | null;
  /**
   * Optional web authentication account.
   */
  user?: (number | null) | User;
  notificationPreferences?: {
    emailNotifications?: boolean | null;
    dashboardNotifications?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  /**
   * Authoritative patient identity record.
   */
  client: number | Client;
  /**
   * Assigned specialist or attending dentist (optional until scheduled).
   */
  doctor?: (number | null) | Doctor;
  /**
   * Associated clinical service context (optional).
   */
  service?: (number | null) | Service;
  dateTime: string;
  /**
   * Initial operational visit classification.
   */
  appointmentType: 'consultation' | 'treatment' | 'followup' | 'routine_checkup' | 'emergency';
  /**
   * Server-enforced operational lifecycle state.
   */
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  /**
   * Operational appointment metadata (does not prevent scheduling conflicts).
   */
  duration?: number | null;
  /**
   * Administrative and operational notes for the encounter.
   */
  notes?: string | null;
  /**
   * Mandatory documentation when appointment is cancelled.
   */
  cancellationReason?: string | null;
  /**
   * Flag indicating post-encounter follow-up action is needed.
   */
  followUpRequired?: boolean | null;
  /**
   * Clinical or administrative follow-up instructions.
   */
  followUpNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups".
 */
export interface FollowUp {
  id: number;
  /**
   * Authoritative patient identity record.
   */
  client: number | Client;
  /**
   * Associated appointment encounter context (optional).
   */
  appointment?: (number | null) | Appointment;
  /**
   * Target date for the follow-up interaction. Purely operational metadata.
   */
  dueDate: string;
  /**
   * Operational classification of the follow-up action.
   */
  followUpType: 'clinical_check' | 'suture_removal' | 'treatment_review' | 'routine_recall' | 'administrative';
  /**
   * Server-enforced operational lifecycle state.
   */
  status: 'pending' | 'contacted' | 'completed' | 'cancelled';
  /**
   * Administrative and operational notes regarding this follow-up.
   */
  notes?: string | null;
  /**
   * Operational result of the contact/interaction. Must not be used for clinical diagnoses or medical records.
   */
  outcome?: string | null;
  /**
   * Mandatory documentation when follow-up is cancelled.
   */
  cancellationReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: number;
  /**
   * Authoritative patient identity record.
   */
  client: number | Client;
  /**
   * Attending dentist or specialist who conducted the consultation.
   */
  doctor?: (number | null) | Doctor;
  /**
   * Associated appointment encounter context (optional).
   */
  appointment?: (number | null) | Appointment;
  /**
   * Date the clinical examination was performed.
   */
  consultationDate: string;
  /**
   * Operational classification of the clinical consultation.
   */
  consultationType:
    | 'initial_examination'
    | 'comprehensive_evaluation'
    | 'treatment_planning'
    | 'specialist_consult'
    | 'clinical_review';
  /**
   * Server-enforced operational lifecycle state.
   */
  status: 'draft' | 'completed' | 'cancelled';
  /**
   * Patient's primary stated concern or reason for visit.
   */
  chiefComplaint?: string | null;
  /**
   * General clinical examination observations and intraoral findings.
   */
  clinicalNotes?: string | null;
  /**
   * Verbal clinical recommendations and treatment plan outline discussed with the patient.
   */
  recommendations?: string | null;
  /**
   * Mandatory documentation when consultation is cancelled.
   */
  cancellationReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  /**
   * Official document title (e.g. Comprehensive Periodontal Assessment, Specialist Referral).
   */
  title: string;
  /**
   * Authoritative patient identity record.
   */
  client: number | Client;
  /**
   * Dentist or specialist issuing the report (optional).
   */
  doctor?: (number | null) | Doctor;
  /**
   * Originating clinical consultation encounter (optional).
   */
  consultation?: (number | null) | Consultation;
  /**
   * Associated appointment encounter context (optional).
   */
  appointment?: (number | null) | Appointment;
  /**
   * Official date of report issuance.
   */
  reportDate: string;
  /**
   * Official classification of the document.
   */
  reportType: 'clinical_summary' | 'referral_letter';
  /**
   * Server-enforced operational lifecycle state.
   */
  status: 'draft' | 'finalized' | 'cancelled';
  /**
   * Official text, findings summary, or clinical statement.
   */
  summary?: string | null;
  /**
   * Optional uploaded document or official signed PDF file.
   */
  attachment?: (number | null) | Media;
  /**
   * Mandatory documentation when report is cancelled.
   */
  cancellationReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal transactional email delivery outbox for reliable, durable, and retryable email notifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-outbox".
 */
export interface EmailOutbox {
  id: number;
  /**
   * Destination email address.
   */
  to: string;
  subject: string;
  html: string;
  text?: string | null;
  /**
   * Unique business event reference (e.g. inquiry-123) to prevent duplicate delivery.
   */
  referenceId?: string | null;
  status: 'pending' | 'processing' | 'sent' | 'failed';
  /**
   * Number of SMTP transmission attempts made (max: 3).
   */
  attempts: number;
  /**
   * Error diagnostics recorded from the last failed delivery attempt.
   */
  lastError?: string | null;
  /**
   * Scheduled timestamp for the next automated retry attempt.
   */
  nextRetryAt?: string | null;
  /**
   * Timestamp when the message was successfully accepted by SMTP.
   */
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'youtube-videos';
        value: number | YoutubeVideo;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null)
    | ({
        relationTo: 'follow-ups';
        value: number | FollowUp;
      } | null)
    | ({
        relationTo: 'consultations';
        value: number | Consultation;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'email-outbox';
        value: number | EmailOutbox;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  featuredImage?: T;
  iconName?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  bio?: T;
  photo?: T;
  specialties?: T;
  qualifications?:
    | T
    | {
        degree?: T;
        id?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-videos_select".
 */
export interface YoutubeVideosSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  thumbnail?: T;
  category?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  service?: T;
  preferredDate?: T;
  preferredTime?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  dateOfBirth?: T;
  gender?: T;
  address?: T;
  emergencyContact?:
    | T
    | {
        name?: T;
        relationship?: T;
        phone?: T;
      };
  status?: T;
  internalNotes?: T;
  user?: T;
  notificationPreferences?:
    | T
    | {
        emailNotifications?: T;
        dashboardNotifications?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  client?: T;
  doctor?: T;
  service?: T;
  dateTime?: T;
  appointmentType?: T;
  status?: T;
  duration?: T;
  notes?: T;
  cancellationReason?: T;
  followUpRequired?: T;
  followUpNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups_select".
 */
export interface FollowUpsSelect<T extends boolean = true> {
  client?: T;
  appointment?: T;
  dueDate?: T;
  followUpType?: T;
  status?: T;
  notes?: T;
  outcome?: T;
  cancellationReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  client?: T;
  doctor?: T;
  appointment?: T;
  consultationDate?: T;
  consultationType?: T;
  status?: T;
  chiefComplaint?: T;
  clinicalNotes?: T;
  recommendations?: T;
  cancellationReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  doctor?: T;
  consultation?: T;
  appointment?: T;
  reportDate?: T;
  reportType?: T;
  status?: T;
  summary?: T;
  attachment?: T;
  cancellationReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-outbox_select".
 */
export interface EmailOutboxSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  html?: T;
  text?: T;
  referenceId?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  nextRetryAt?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroBadge?: string | null;
  heroTitle: string;
  heroSubtitle?: string | null;
  overviewTitle?: string | null;
  overviewText?: string | null;
  overviewImage?: (number | null) | Media;
  whyChooseTitle?: string | null;
  whyChooseSubtitle?: string | null;
  whyChooseItems?:
    | {
        title: string;
        description?: string | null;
        iconName?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Verified operational statistics or clinic metrics. If empty, the statistics bar remains non-promissory or displays verified defaults.
   */
  trustStats?:
    | {
        value: string;
        label: string;
        iconKey?: ('users' | 'star' | 'award' | 'heartHandshake' | 'shield' | 'clock') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Curated clinical case photos demonstrating before and after dental results. Click row to edit case details.
   */
  beforeAfterCases?:
    | {
        title: string;
        beforeImage: number | Media;
        afterImage: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaHeadline?: string | null;
  ctaSubtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  storyTitle?: string | null;
  storyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  storyImage?: (number | null) | Media;
  founderTitle?: string | null;
  founderQuote?: string | null;
  founderName?: string | null;
  founderRole?: string | null;
  mission?: string | null;
  vision?: string | null;
  positioning?: string | null;
  valuesTitle?: string | null;
  /**
   * The clinic fundamental values guiding clinical decisions and patient care.
   */
  coreValues?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  experienceNarrative?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info".
 */
export interface ClinicInfo {
  id: number;
  clinicName: string;
  email?: string | null;
  address?: string | null;
  /**
   * Google Maps embed link or directions URL.
   */
  locationOnMap?: string | null;
  phoneNumbers?:
    | {
        number: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  openingHours?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  overviewTitle?: T;
  overviewText?: T;
  overviewImage?: T;
  whyChooseTitle?: T;
  whyChooseSubtitle?: T;
  whyChooseItems?:
    | T
    | {
        title?: T;
        description?: T;
        iconName?: T;
        id?: T;
      };
  trustStats?:
    | T
    | {
        value?: T;
        label?: T;
        iconKey?: T;
        id?: T;
      };
  beforeAfterCases?:
    | T
    | {
        title?: T;
        beforeImage?: T;
        afterImage?: T;
        description?: T;
        id?: T;
      };
  ctaHeadline?: T;
  ctaSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  storyTitle?: T;
  storyContent?: T;
  storyImage?: T;
  founderTitle?: T;
  founderQuote?: T;
  founderName?: T;
  founderRole?: T;
  mission?: T;
  vision?: T;
  positioning?: T;
  valuesTitle?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  experienceNarrative?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info_select".
 */
export interface ClinicInfoSelect<T extends boolean = true> {
  clinicName?: T;
  email?: T;
  address?: T;
  locationOnMap?: T;
  phoneNumbers?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}